// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WORLD_OF_DUEL_MASTERS.Models;

namespace WORLD_OF_DUEL_MASTERS.Migrations
{
    [DbContext(typeof(MyDatabaseContext))]
    [Migration("20190525052423_MyDatabaseMigration")]
    partial class MyDatabaseMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WORLD_OF_DUEL_MASTERS.Models.Account", b =>
                {
                    b.Property<Guid>("AccountID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Type");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("AccountID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("WORLD_OF_DUEL_MASTERS.Models.Card", b =>
                {
                    b.Property<Guid>("CardID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Civilization")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Civilizations0")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Civilizations1")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Cost")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid>("DeckID");

                    b.Property<string>("Flavor")
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Illustrator")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Power")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Race")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Races0")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Races1")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Set")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CardID");

                    b.HasIndex("DeckID");

                    b.ToTable("Card");
                });

            modelBuilder.Entity("WORLD_OF_DUEL_MASTERS.Models.DMCard", b =>
                {
                    b.Property<int>("CardID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Civilization")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Civilizations0")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Civilizations1")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Cost")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Flavor")
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Illustrator")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Power")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Race")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Races0")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Races1")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Set")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CardID");

                    b.ToTable("DMCards");
                });

            modelBuilder.Entity("WORLD_OF_DUEL_MASTERS.Models.Deck", b =>
                {
                    b.Property<Guid>("DeckID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountID");

                    b.Property<string>("Name");

                    b.HasKey("DeckID");

                    b.HasIndex("AccountID");

                    b.ToTable("Deck");
                });

            modelBuilder.Entity("WORLD_OF_DUEL_MASTERS.Models.Card", b =>
                {
                    b.HasOne("WORLD_OF_DUEL_MASTERS.Models.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WORLD_OF_DUEL_MASTERS.Models.Deck", b =>
                {
                    b.HasOne("WORLD_OF_DUEL_MASTERS.Models.Account", "Account")
                        .WithMany("Decks")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
